name: main
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
permissions:
  actions: read
  checks: write
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Get faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh
      - name: Pull custom templates
        run: faas-cli template pull https://github.com/Cheivin/wechat-assistant-plugin-templates
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build functions
        run: >
          faas-cli build
          --build-arg GO111MODULE=on
      - name: Push functions
        run: >
          faas-cli push
      - name: Login
        run: >
          echo ${{secrets.OPENFAAS_PASSWORD}} | 
          faas-cli login --gateway ${{secrets.OPENFAAS_URL}} --password-stdin
      - name: Deploy
        run: >
          faas-cli deploy --gateway ${{secrets.OPENFAAS_URL}}
